services:
  ankaios-server:
    build:
      context: .
      dockerfile: Dockerfile.ankaios
    platform: linux/arm64
    container_name: ankaios-server
    environment:
      - ARCH=arm64
      - LOG_LEVEL=info
    volumes:
      - ./manifests:/manifests
      - ./logs:/logs
    command: ank-server --address 0.0.0.0:25551
    ports:
      - "25551:25551"
    networks:
      - ota-net
    restart: unless-stopped

  ankaios-agent-cluster:
    build:
      context: .
      dockerfile: Dockerfile.ankaios
    platform: linux/arm64
    container_name: ankaios-agent-cluster
    environment:
      - ARCH=arm64
      - LOG_LEVEL=info
    volumes:
      - ./manifests:/manifests
      - ./tests:/tests
      - ./logs:/logs
      - /var/run/podman/podman.sock:/var/run/podman/podman.sock
    command: ank-agent --server-address ankaios-server:25551 --name instrument-cluster
    depends_on:
      - ankaios-server
    networks:
      - ota-net
    restart: unless-stopped
    privileged: true

  mock-cloud:
    image: python:3.9-slim
    platform: linux/arm64
    container_name: mock-cloud
    volumes:
      - ./scripts:/scripts
      - ./manifests:/manifests
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep 10 && python /scripts/mock-cloud.py"]
    networks:
      - ota-net
    restart: unless-stopped

networks:
  ota-net:
    driver: bridge
